# Generated by Django 3.2.7 on 2021-09-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotelapp', '0002_hotel_hotel_image'),
        ('Productapp', '0003_auto_20210922_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_product', to='Hotelapp.hotel'),
        ),
    ]
