# Generated by Django 3.2.7 on 2021-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0004_alter_product_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hotel_image',
            field=models.ImageField(blank=True, upload_to='hotel_image'),
        ),
    ]
